#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

#
# If second HDMI display is connected, setup screens and plit workspaces
#
if [[ $(xrandr -q | grep -w 'HDMI-A-0 connected') ]]; then
    # Mainz home setup (righ 2K screen)
	xrandr --output HDMI-A-0 --primary --mode 2560x1440 --rotate normal --output eDP --mode 1920x1080 --rotate normal --left-of HDMI-A-0	
	bspc monitor HDMI-A-0 -d VI VII VIII IX X
	bspc monitor eDP      -d I II III IV V

	# Bologna home setup (right FHD screen)
	# xrandr --output HDMI-A-0 --primary --mode 1920x1080 --rotate normal --output eDP --mode 1920x1080 --rotate normal --left-of HDMI-A-0
	# bspc monitor HDMI-A-0 -d VI VII VIII IX X
	# bspc monitor eDP      -d I II III IV V

	# Sunny office setup (left FHD screen)
	# xrandr --output HDMI-A-0 --primary --mode 1920x1080 --rotate normal --output eDP --mode 1920x1080 --rotate normal --right-of HDMI-A-0
	# bspc monitor HDMI-A-0 -d VI VII VIII IX X
	# bspc monitor eDP      -d I II III IV V
else
    # Only laptop
	bspc monitor -d I II III IV V
fi





bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true

bspc rule -a Zoom desktop='^10'
bspc rule -a mplayer2 state=floating
bspc rule -a Yad state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


# Border
bspc config focused_border_color        "#bbeeeeee"
bspc config normal_border_color         "#0d2b0d"
bspc config active_border_color         "#0d2b0d"

#
# Autostart
#
# Set display from arandr saved script
sh ~/.screenlayout/monitor.sh &

# Bar
# ~/.config/polybar/launch.sh &
eww open bar

# Notifications
/usr/bin/dunst &

# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Wallpaper
nitrogen --restore &

# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/  

# Picom
picom -CGb &

# Network Applet
nm-applet --indicator &

# Cursor
xsetroot -cursor_name left_ptr &

# Low battery notifier
~/.config/bspwm/scripts/low_bat_notifier.sh

# No wierd errorbells
xset -b
setterm -blength 0
set errorbell none
