#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus false
bspc config focus_follows_pointer true


bspc rule -a '*' state=floating
bspc rule -a kitty state=tiled
bspc rule -a thunderbird state=tiled
bspc rule -a VSCodium state=tiled
bspc rule -a Brave-browser state=tiled
bspc rule -a firefox state=tiled

bspc rule -a Screenkey manage=off

# bspc rule -a Tk state=floating
# bspc rule -a  state=floating
# bspc rule -a Matplotlib state=floating
# bspc rule -a Gnome-screenshot state=floating
# bspc rule -a Yad state=floating
# bspc rule -a Kupfer.py focus=on


# Border
#bspc config focused_border_color        "#bbeeeeee"
bspc config focused_border_color        "#00000000"
bspc config normal_border_color         "#00000000"
bspc config active_border_color         "#00000b00"

#
# Autostart
#
# Set display from arandr saved script
sh ~/.screenlayout/bspwm-layout.sh &

# Bar
~/.config/polybar/launch.sh &
# eww open bar

# Notifications
/usr/bin/dunst &

# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Wallpaper
nitrogen --restore &

# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/  

# Picom
picom -CGb &

# Network Applet
nm-applet --indicator &

# Cursor
xsetroot -cursor_name left_ptr &

# Low battery notifier
~/.config/bspwm/scripts/low_bat_notifier.sh

# No weird errorbells
xset -b
setterm -blength 0
set errorbell none
